post_list:
    path: /posts
    controller: App\Controller\PostsController::getPosts
    methods: [GET]

post_create:
    path: /posts
    controller: App\Controller\PostsController::createPost
    methods: [POST]

post_show:
    path: /posts/{id}
    controller: App\Controller\PostsController::getPostById
    methods: [Get]